version: 1
update_configs:
  - package_manager: "java:maven"
    directory: "/"
    update_schedule: "weekly"
    ignored_updates:
      - match:
          dependency_name: "javax.measure:unit-api"
          version_requirement: "2.0-PRD"
      - match:
          dependency_name: "javax.measure:unit-api"
          version_requirement: "2.0-EDR"
